'use client';
// import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

//just like layout.tsx, template.tsx does the same thing
// but, whenever page changes eberything re-renders 9 running use Effects again ]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();

  return (
    <html lang='en'>
      <body
        className={`flex flex-col items-center ${geistSans.variable} ${geistMono.variable} antialiased `}>
        <header className='flex justify-center'>
          <nav className='flex bg-orange-500 text-white p-2 m-2 shadow-md gap-4'>
            <Link
              href='/about'
              className={
                pathName.includes('about') ? 'border-b-4 border-white' : ''
              }>
              About
            </Link>
            <Link href='/profile/teams'>Profile</Link>
            <Link href='/services'>Services</Link>
            <Link
              href='/posts'
              className={
                pathName.includes('posts') ? 'border-b-4 border-white' : ''
              }>
              Posts
            </Link>
            <Link
              href='/products'
              className={
                pathName.includes('products') ? 'border-b-4 border-white' : ''
              }>
              Products
            </Link>
          </nav>
        </header>
        <div className='flex flex-col items-center'>{children}</div>
        <footer>Footer section</footer>
      </body>
    </html>
  );
}
